config/routes.rb
Rails.application.routes.draw do
  resources :questionarios
  resources :questaos
  resources :pacientes
  resources :profissionals
  resources :pessoas
  root to: "home#index"
  devise_for :users
  resources :tiposervicos
  resources :estadocivils
  resources :generos
  resources :tipocancers
  resources :produtos
  resources :escolaridades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/escolaridade.rb
class Escolaridade < ApplicationRecord
  
end

app/models/estadocivil.rb
class Estadocivil < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/paciente.rb
class Paciente < Pessoa
  belongs_to :pessoa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/profissional.rb
class Profissional < Pessoa
  belongs_to :pessoa
end

app/models/questao.rb
class Questao < ApplicationRecord
end

app/models/questionario.rb
class Questionario < ApplicationRecord
end

app/models/tipocancer.rb
class Tipocancer < ApplicationRecord
end

app/models/tiposervico.rb
class Tiposervico < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
   def index
    
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < PessoasController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:pessoa_id, :numerocartaosus, :profissao, :enderecoprofissional, :enderecoresidencial, :nomeconjugue, :contatoconjugue, :string, :profissaoconjugue, :possuifilhos, :filhosquantidade, :idadefilhos, :observacao, :localnascimento, :datacadastro, :dataobito, :ativo)
    end
end

app/helpers/anexos_helper.rb
module AnexosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/questaos_helper.rb
module QuestaosHelper
end

app/helpers/tipocancers_helper.rb
module TipocancersHelper
end

app/views/pacientes/_form.html.erb
<%= form_for(paciente) do |f| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pessoa_id %>
    <%= f.text_field :pessoa_id %>
  </div>

  <div class="field">
    <%= f.label :numerocartaosus %>
    <%= f.text_field :numerocartaosus %>
  </div>

  <div class="field">
    <%= f.label :profissao %>
    <%= f.text_field :profissao %>
  </div>

  <div class="field">
    <%= f.label :enderecoprofissional %>
    <%= f.text_field :enderecoprofissional %>
  </div>

  <div class="field">
    <%= f.label :enderecoresidencial %>
    <%= f.text_field :enderecoresidencial %>
  </div>

  <div class="field">
    <%= f.label :nomeconjugue %>
    <%= f.text_field :nomeconjugue %>
  </div>

  <div class="field">
    <%= f.label :contatoconjugue %>
    <%= f.text_field :contatoconjugue %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :profissaoconjugue %>
    <%= f.text_field :profissaoconjugue %>
  </div>

  <div class="field">
    <%= f.label :possuifilhos %>
    <%= f.check_box :possuifilhos %>
  </div>

  <div class="field">
    <%= f.label :filhosquantidade %>
    <%= f.number_field :filhosquantidade %>
  </div>

  <div class="field">
    <%= f.label :idadefilhos %>
    <%= f.text_field :idadefilhos %>
  </div>

  <div class="field">
    <%= f.label :observacao %>
    <%= f.text_field :observacao %>
  </div>

  <div class="field">
    <%= f.label :localnascimento %>
    <%= f.text_field :localnascimento %>
  </div>

  <div class="field">
    <%= f.label :datacadastro %>
    <%= f.datetime_select :datacadastro %>
  </div>

  <div class="field">
    <%= f.label :dataobito %>
    <%= f.date_select :dataobito %>
  </div>

  <div class="field">
    <%= f.label :ativo %>
    <%= f.check_box :ativo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Pessoa</th>
      <th>Numerocartaosus</th>
      <th>Profissao</th>
      <th>Enderecoprofissional</th>
      <th>Enderecoresidencial</th>
      <th>Nomeconjugue</th>
      <th>Contatoconjugue</th>
      <th>String</th>
      <th>Profissaoconjugue</th>
      <th>Possuifilhos</th>
      <th>Filhosquantidade</th>
      <th>Idadefilhos</th>
      <th>Observacao</th>
      <th>Localnascimento</th>
      <th>Datacadastro</th>
      <th>Dataobito</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.pessoa %></td>
        <td><%= paciente.numerocartaosus %></td>
        <td><%= paciente.profissao %></td>
        <td><%= paciente.enderecoprofissional %></td>
        <td><%= paciente.enderecoresidencial %></td>
        <td><%= paciente.nomeconjugue %></td>
        <td><%= paciente.contatoconjugue %></td>
        <td><%= paciente.string %></td>
        <td><%= paciente.profissaoconjugue %></td>
        <td><%= paciente.possuifilhos %></td>
        <td><%= paciente.filhosquantidade %></td>
        <td><%= paciente.idadefilhos %></td>
        <td><%= paciente.observacao %></td>
        <td><%= paciente.localnascimento %></td>
        <td><%= paciente.datacadastro %></td>
        <td><%= paciente.dataobito %></td>
        <td><%= paciente.ativo %></td>
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>New Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pessoa:</strong>
  <%= @paciente.pessoa %>
</p>

<p>
  <strong>Numerocartaosus:</strong>
  <%= @paciente.numerocartaosus %>
</p>

<p>
  <strong>Profissao:</strong>
  <%= @paciente.profissao %>
</p>

<p>
  <strong>Enderecoprofissional:</strong>
  <%= @paciente.enderecoprofissional %>
</p>

<p>
  <strong>Enderecoresidencial:</strong>
  <%= @paciente.enderecoresidencial %>
</p>

<p>
  <strong>Nomeconjugue:</strong>
  <%= @paciente.nomeconjugue %>
</p>

<p>
  <strong>Contatoconjugue:</strong>
  <%= @paciente.contatoconjugue %>
</p>

<p>
  <strong>String:</strong>
  <%= @paciente.string %>
</p>

<p>
  <strong>Profissaoconjugue:</strong>
  <%= @paciente.profissaoconjugue %>
</p>

<p>
  <strong>Possuifilhos:</strong>
  <%= @paciente.possuifilhos %>
</p>

<p>
  <strong>Filhosquantidade:</strong>
  <%= @paciente.filhosquantidade %>
</p>

<p>
  <strong>Idadefilhos:</strong>
  <%= @paciente.idadefilhos %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @paciente.observacao %>
</p>

<p>
  <strong>Localnascimento:</strong>
  <%= @paciente.localnascimento %>
</p>

<p>
  <strong>Datacadastro:</strong>
  <%= @paciente.datacadastro %>
</p>

<p>
  <strong>Dataobito:</strong>
  <%= @paciente.dataobito %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @paciente.ativo %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>