config/routes.rb
Rails.application.routes.draw do
  resources :questionarios
  resources :questaos
  resources :pacientes
  resources :profissionals
  resources :pessoas
  root to: "home#index"
  devise_for :users
  resources :tiposervicos
  resources :estadocivils
  resources :generos
  resources :tipocancers
  resources :produtos
  resources :escolaridades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/escolaridade.rb
class Escolaridade < ApplicationRecord
  
end

app/models/estadocivil.rb
class Estadocivil < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/paciente.rb
class Paciente < Pessoa
  belongs_to :pessoa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/profissional.rb
class Profissional < Pessoa
  belongs_to :pessoa
end

app/models/questao.rb
class Questao < ApplicationRecord
end

app/models/questionario.rb
class Questionario < ApplicationRecord
end

app/models/tipocancer.rb
class Tipocancer < ApplicationRecord
end

app/models/tiposervico.rb
class Tiposervico < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/profissionals_controller.rb
class ProfissionalsController < PessoasController
  before_action :set_profissional, only: [:show, :edit, :update, :destroy]

  # GET /profissionals
  # GET /profissionals.json
  def index
    @profissionals = Profissional.all
  end

  # GET /profissionals/1
  # GET /profissionals/1.json
  def show
  end

  # GET /profissionals/new
  def new
    @profissional = Profissional.new
  end

  # GET /profissionals/1/edit
  def edit
  end

  # POST /profissionals
  # POST /profissionals.json
  def create
    @profissional = Profissional.new(profissional_params)

    respond_to do |format|
      if @profissional.save
        format.html { redirect_to @profissional, notice: 'Profissional was successfully created.' }
        format.json { render :show, status: :created, location: @profissional }
      else
        format.html { render :new }
        format.json { render json: @profissional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profissionals/1
  # PATCH/PUT /profissionals/1.json
  def update
    respond_to do |format|
      if @profissional.update(profissional_params)
        format.html { redirect_to @profissional, notice: 'Profissional was successfully updated.' }
        format.json { render :show, status: :ok, location: @profissional }
      else
        format.html { render :edit }
        format.json { render json: @profissional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profissionals/1
  # DELETE /profissionals/1.json
  def destroy
    @profissional.destroy
    respond_to do |format|
      format.html { redirect_to profissionals_url, notice: 'Profissional was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profissional
      @profissional = Profissional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profissional_params
      params.require(:profissional).permit(:especializacao, :pessoa_id)
    end
end

app/helpers/anexos_helper.rb
module AnexosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/profissionals_helper.rb
module ProfissionalsHelper
end

app/helpers/questaos_helper.rb
module QuestaosHelper
end

app/helpers/tipocancers_helper.rb
module TipocancersHelper
end

app/views/profissionals/_form.html.erb
<%= form_for(profissional) do |f| %>
  <% if profissional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profissional.errors.count, "error") %> prohibited this profissional from being saved:</h2>

      <ul>
      <% profissional.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :especializacao %>
    <%= f.text_field :especializacao %>
  </div>

  <div class="field">
    <%= f.label :pessoa_id %>
    <%= f.text_field :pessoa_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profissionals/edit.html.erb
<h1>Editing Profissional</h1>

<%= render 'form', profissional: @profissional %>

<%= link_to 'Show', @profissional %> |
<%= link_to 'Back', profissionals_path %>

app/views/profissionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profissionals</h1>

<table>
  <thead>
    <tr>
      <th>Especializacao</th>
      <th>Pessoa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profissionals.each do |profissional| %>
      <tr>
        <td><%= profissional.especializacao %></td>
        <td><%= profissional.pessoa %></td>
        <td><%= link_to 'Show', profissional %></td>
        <td><%= link_to 'Edit', edit_profissional_path(profissional) %></td>
        <td><%= link_to 'Destroy', profissional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profissional', new_profissional_path %>

app/views/profissionals/new.html.erb
<h1>New Profissional</h1>

<%= render 'form', profissional: @profissional %>

<%= link_to 'Back', profissionals_path %>

app/views/profissionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Especializacao:</strong>
  <%= @profissional.especializacao %>
</p>

<p>
  <strong>Pessoa:</strong>
  <%= @profissional.pessoa %>
</p>

<%= link_to 'Edit', edit_profissional_path(@profissional) %> |
<%= link_to 'Back', profissionals_path %>