config/routes.rb
Rails.application.routes.draw do
  resources :questionarios
  resources :questaos
  resources :pacientes
  resources :profissionals
  resources :pessoas
  root to: "home#index"
  devise_for :users
  resources :tiposervicos
  resources :estadocivils
  resources :generos
  resources :tipocancers
  resources :produtos
  resources :escolaridades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/escolaridade.rb
class Escolaridade < ApplicationRecord
  
end

app/models/estadocivil.rb
class Estadocivil < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/paciente.rb
class Paciente < Pessoa
  belongs_to :pessoa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/profissional.rb
class Profissional < Pessoa
  belongs_to :pessoa
end

app/models/questao.rb
class Questao < ApplicationRecord
end

app/models/questionario.rb
class Questionario < ApplicationRecord
end

app/models/tipocancer.rb
class Tipocancer < ApplicationRecord
end

app/models/tiposervico.rb
class Tiposervico < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
   def index
    
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :cpf, :rg, :telefoneresidencial, :telefonecelular, :datanascimento, :sexo)
    end
end

app/helpers/anexos_helper.rb
module AnexosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/questaos_helper.rb
module QuestaosHelper
end

app/helpers/tipocancers_helper.rb
module TipocancersHelper
end

app/views/pessoas/_form.html.erb
<%= form_for(pessoa) do |f| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :rg %>
    <%= f.text_field :rg %>
  </div>

  <div class="field">
    <%= f.label :telefoneresidencial %>
    <%= f.text_field :telefoneresidencial %>
  </div>

  <div class="field">
    <%= f.label :telefonecelular %>
    <%= f.text_field :telefonecelular %>
  </div>

  <div class="field">
    <%= f.label :datanascimento %>
    <%= f.date_select :datanascimento %>
  </div>

  <div class="field">
    <%= f.label :sexo %>
    <%= f.number_field :sexo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Telefoneresidencial</th>
      <th>Telefonecelular</th>
      <th>Datanascimento</th>
      <th>Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.cpf %></td>
        <td><%= pessoa.rg %></td>
        <td><%= pessoa.telefoneresidencial %></td>
        <td><%= pessoa.telefonecelular %></td>
        <td><%= pessoa.datanascimento %></td>
        <td><%= pessoa.sexo %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @pessoa.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @pessoa.rg %>
</p>

<p>
  <strong>Telefoneresidencial:</strong>
  <%= @pessoa.telefoneresidencial %>
</p>

<p>
  <strong>Telefonecelular:</strong>
  <%= @pessoa.telefonecelular %>
</p>

<p>
  <strong>Datanascimento:</strong>
  <%= @pessoa.datanascimento %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @pessoa.sexo %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>