config/routes.rb
Rails.application.routes.draw do
  resources :questionarios
  resources :questaos
  resources :pacientes
  resources :profissionals
  resources :pessoas
  root to: "home#index"
  devise_for :users
  resources :tiposervicos
  resources :estadocivils
  resources :generos
  resources :tipocancers
  resources :produtos
  resources :escolaridades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/escolaridade.rb
class Escolaridade < ApplicationRecord
  
end

app/models/estadocivil.rb
class Estadocivil < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/paciente.rb
class Paciente < Pessoa
  belongs_to :pessoa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/profissional.rb
class Profissional < Pessoa
  belongs_to :pessoa
end

app/models/questao.rb
class Questao < ApplicationRecord
end

app/models/questionario.rb
class Questionario < ApplicationRecord
end

app/models/tipocancer.rb
class Tipocancer < ApplicationRecord
end

app/models/tiposervico.rb
class Tiposervico < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/tiposervicos_controller.rb
class TiposervicosController < ApplicationController
  before_action :set_tiposervico, only: [:show, :edit, :update, :destroy]

  # GET /tiposervicos
  # GET /tiposervicos.json
  def index
    @tiposervicos = Tiposervico.all
  end

  # GET /tiposervicos/1
  # GET /tiposervicos/1.json
  def show
  end

  # GET /tiposervicos/new
  def new
    @tiposervico = Tiposervico.new
  end

  # GET /tiposervicos/1/edit
  def edit
  end

  # POST /tiposervicos
  # POST /tiposervicos.json
  def create
    @tiposervico = Tiposervico.new(tiposervico_params)

    respond_to do |format|
      if @tiposervico.save
        format.html { redirect_to @tiposervico, notice: 'Tiposervico was successfully created.' }
        format.json { render :show, status: :created, location: @tiposervico }
      else
        format.html { render :new }
        format.json { render json: @tiposervico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiposervicos/1
  # PATCH/PUT /tiposervicos/1.json
  def update
    respond_to do |format|
      if @tiposervico.update(tiposervico_params)
        format.html { redirect_to @tiposervico, notice: 'Tiposervico was successfully updated.' }
        format.json { render :show, status: :ok, location: @tiposervico }
      else
        format.html { render :edit }
        format.json { render json: @tiposervico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiposervicos/1
  # DELETE /tiposervicos/1.json
  def destroy
    @tiposervico.destroy
    respond_to do |format|
      format.html { redirect_to tiposervicos_url, notice: 'Tiposervico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tiposervico
      @tiposervico = Tiposervico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tiposervico_params
      params.require(:tiposervico).permit(:descricao)
    end
end

app/helpers/anexos_helper.rb
module AnexosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/questaos_helper.rb
module QuestaosHelper
end

app/helpers/tipocancers_helper.rb
module TipocancersHelper
end

app/helpers/tiposervicos_helper.rb
module TiposervicosHelper
end

app/views/tiposervicos/_form.html.erb
<%= form_for @tiposervico, :html => { :class => "form-horizontal tiposervico" } do |f| %>

  <% if @tiposervico.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tiposervico.errors.count, "error") %> prohibited this tiposervico from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tiposervico.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tiposervicos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tiposervicos/edit.html.erb
<%- model_class = Tiposervico -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tiposervicos/index.html.erb
<%- model_class = Tiposervico -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tiposervicos.each do |tiposervico| %>
      <tr>
        <td><%= link_to tiposervico.id, tiposervico_path(tiposervico) %></td>
        <td><%= tiposervico.descricao %></td>
        <td><%=l tiposervico.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      tiposervico_path(tiposervico), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tiposervico_path(tiposervico), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tiposervico_path(tiposervico),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tiposervico_path,
            :class => 'btn btn-primary' %>

app/views/tiposervicos/new.html.erb
<%- model_class = Tiposervico -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tiposervicos/show.html.erb
<%- model_class = Tiposervico -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @tiposervico.descricao %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tiposervicos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tiposervico_path(@tiposervico), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tiposervico_path(@tiposervico),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>